import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { rollDice, wrapBareDiceInBackticks } from '../../../../common/dice'
import { InlineDiceRoll } from '../dice/InlineDiceRoll'
import { parseNote } from '../../../../common/frontmatter'
import { stripStructuredSections } from '../../../../common/noteTypes/language'
import type { NoteRefApi } from '../../lib/noteRefApi'

// Excludes [[timeline: ...]] mentions (see common/worldTimeline.ts) via a
// negative lookahead — those are a distinct marker, rendered separately
// below, not a note reference.
const WIKI_LINK_RE = /\[\[(?!\s*timeline\s*:)([^\]|#]+)(?:#[^\]|]*)?(?:\|([^\]]*))?\]\]/gi
const INLINE_TIMELINE_RE = /\[\[timeline:\s*([^\]]+)\]\]/gi

// Rewrites [[Title]] / [[Title|Alias]] into ordinary markdown links pointing
// at a "wikilink:" pseudo-URL, which the custom `a` renderer below
// intercepts instead of letting the browser try to navigate to it.
function convertWikiLinksToMarkdown(content: string): string {
  return content.replace(WIKI_LINK_RE, (_match, title: string, alias?: string) => {
    const targetTitle = title.trim()
    const label = (alias ?? targetTitle).trim()
    return `[${label}](wikilink:${encodeURIComponent(targetTitle)})`
  })
}

// Renders [[timeline: <date>: <description>]] as plain styled text — no
// note to link to, just a visual marker that this line is on the timeline
// (see session.ts's listEvents, which extracts the same syntax).
function convertInlineTimelineToMarkdown(content: string): string {
  return content.replace(INLINE_TIMELINE_RE, (match, inner: string) => {
    const idx = inner.indexOf(': ')
    if (idx === -1) return match
    const date = inner.slice(0, idx).trim()
    const description = inner.slice(idx + 2).trim()
    return `**📅 ${date}:** ${description}`
  })
}

export function PreviewPane({ content, noteRefApi }: { content: string; noteRefApi: NoteRefApi }): React.JSX.Element {
  const handleWikiLinkClick = noteRefApi.openByTitle

  const { frontmatter, body } = parseNote(content)
  // Language notes show their "## Word: ..." and "## Grammar: ..." sections
  // in the structured Dictionary/Grammar panels above the editor —
  // rendering them again here as raw headings would just be the same
  // content twice.
  const previewBody = frontmatter.type === 'language' ? stripStructuredSections(body) : body
  const markdown = convertWikiLinksToMarkdown(convertInlineTimelineToMarkdown(wrapBareDiceInBackticks(previewBody)))

  return (
    <div className="preview-pane">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        // react-markdown sanitizes hrefs by default and strips any
        // protocol outside a small allowlist (http/https/mailto/etc.) —
        // our own "wikilink:" scheme would silently get reduced to an
        // empty string before it ever reached the `a` override below.
        // Safe to disable here: this markdown is generated by us from
        // local file content, not rendering untrusted remote input, and
        // we never let the raw href drive real navigation anyway (see
        // the `a` override — clicks always go through our own handlers).
        urlTransform={(url) => url}
        components={{
          // Deliberately not real <a href> elements: Electron's bare
          // BrowserWindows have no address bar, and letting Chromium
          // navigate (even to a "#" href, and even with preventDefault)
          // can pop a blank native window instead of doing what we want.
          // A non-navigating element sidesteps that whole failure class.
          a: ({ href, children }) => {
            if (href?.startsWith('wikilink:')) {
              const title = decodeURIComponent(href.slice('wikilink:'.length))
              return (
                <span
                  className="wiki-link"
                  role="link"
                  tabIndex={0}
                  onClick={() => void handleWikiLinkClick(title)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') void handleWikiLinkClick(title)
                  }}
                >
                  {children}
                </span>
              )
            }
            return (
              <span
                className="external-link"
                role="link"
                tabIndex={0}
                onClick={() => href && void window.vaultApi.openExternal(href)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && href) void window.vaultApi.openExternal(href)
                }}
              >
                {children}
              </span>
            )
          },
          // Inline code that happens to parse as valid dice notation (e.g.
          // a monster stat block written as "+10 to hit, `3d6+7` damage")
          // becomes clickable-to-roll. Fenced code blocks are unaffected —
          // react-markdown only gives inline code an undefined className,
          // and this also requires the text to be a single line that
          // actually parses, so ordinary code samples never trigger it.
          code: ({ className, children }) => {
            const text = String(children)
            if (!className && !text.includes('\n') && rollDice(text) !== null) {
              return <InlineDiceRoll notation={text} />
            }
            return <code className={className}>{children}</code>
          }
        }}
      >
        {markdown}
      </ReactMarkdown>
    </div>
  )
}
