import ReactMarkdown from 'react-markdown'
import remarkGfm from 'remark-gfm'
import { useEditorStore } from '../../state/editorStore'

const FRONTMATTER_BLOCK = /^---\r?\n[\s\S]*?\r?\n---\r?\n?/
const WIKI_LINK_RE = /\[\[([^\]|#]+)(?:#[^\]|]*)?(?:\|([^\]]*))?\]\]/g

function stripFrontmatter(content: string): string {
  return content.replace(FRONTMATTER_BLOCK, '')
}

// Rewrites [[Title]] / [[Title|Alias]] into ordinary markdown links pointing
// at a "wikilink:" pseudo-URL, which the custom `a` renderer below
// intercepts instead of letting the browser try to navigate to it.
function convertWikiLinksToMarkdown(content: string): string {
  return content.replace(WIKI_LINK_RE, (_match, title: string, alias?: string) => {
    const targetTitle = title.trim()
    const label = (alias ?? targetTitle).trim()
    return `[${label}](wikilink:${encodeURIComponent(targetTitle)})`
  })
}

export function PreviewPane({ content }: { content: string }): React.JSX.Element {
  const openNote = useEditorStore((s) => s.openNote)

  const handleWikiLinkClick = async (title: string): Promise<void> => {
    try {
      const matches = await window.vaultApi.searchTitles(title)
      const exact = matches.find((m) => m.title.toLowerCase() === title.toLowerCase())
      if (exact) {
        await openNote(exact.path)
      } else {
        window.alert(`No note titled "${title}" yet.`)
      }
    } catch (err) {
      window.alert(err instanceof Error ? err.message : String(err))
    }
  }

  const markdown = convertWikiLinksToMarkdown(stripFrontmatter(content))

  return (
    <div className="preview-pane">
      <ReactMarkdown
        remarkPlugins={[remarkGfm]}
        // react-markdown sanitizes hrefs by default and strips any
        // protocol outside a small allowlist (http/https/mailto/etc.) —
        // our own "wikilink:" scheme would silently get reduced to an
        // empty string before it ever reached the `a` override below.
        // Safe to disable here: this markdown is generated by us from
        // local file content, not rendering untrusted remote input, and
        // we never let the raw href drive real navigation anyway (see
        // the `a` override — clicks always go through our own handlers).
        urlTransform={(url) => url}
        components={{
          // Deliberately not real <a href> elements: Electron's bare
          // BrowserWindows have no address bar, and letting Chromium
          // navigate (even to a "#" href, and even with preventDefault)
          // can pop a blank native window instead of doing what we want.
          // A non-navigating element sidesteps that whole failure class.
          a: ({ href, children }) => {
            if (href?.startsWith('wikilink:')) {
              const title = decodeURIComponent(href.slice('wikilink:'.length))
              return (
                <span
                  className="wiki-link"
                  role="link"
                  tabIndex={0}
                  onClick={() => void handleWikiLinkClick(title)}
                  onKeyDown={(e) => {
                    if (e.key === 'Enter') void handleWikiLinkClick(title)
                  }}
                >
                  {children}
                </span>
              )
            }
            return (
              <span
                className="external-link"
                role="link"
                tabIndex={0}
                onClick={() => href && void window.vaultApi.openExternal(href)}
                onKeyDown={(e) => {
                  if (e.key === 'Enter' && href) void window.vaultApi.openExternal(href)
                }}
              >
                {children}
              </span>
            )
          }
        }}
      >
        {markdown}
      </ReactMarkdown>
    </div>
  )
}
